services:
  postgres:
    image: postgres:16
    container_name: eventos_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: eventos_user
      POSTGRES_PASSWORD: eventos_password
      POSTGRES_DB: plataforma_eventos

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: